### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by desertstormx** [FoxInFlame/QuickMyAnimeList#69]
Hi,

When i enter my mal credential and i click on save, it says Successfully logged in! Please wait...

But it never goes through.
I've tried to disable all other extension without success.

I'm on an Acer ChromeBook.
I will try tomorrow to reproduce the issue on my main Windows machine.

**Comment by desertstormx** [comment]
I'm on 1.3.5-0-g3cb7a73

**Comment by FoxInFlame** [comment]
Press Control + Shift + J on the page, and please post any warnings / errors that are on the console.

**Comment by desertstormx** [comment]
Here is the output : 
chrome-extension://hhlboohdmllpkclkmnejcgbahbghdogb/images/default_user.png Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by FoxInFlame** [comment]
That shouldn't be a problem. It was a small bug I found after releasing Version 1.3.5, but you should still be able to login with that warning. Are you sure you still have this issue, and that that is the sole output?

**Comment by FoxInFlame** [comment]
Server side issue. Fixed now.
